# Generated by Django 4.1.3 on 2022-11-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.IntegerField(null=True)),
                ('deleted_by', models.IntegerField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='services_images')),
                ('p1', models.TextField(max_length=1000)),
                ('p2', models.TextField(max_length=1000, null=True)),
                ('p3', models.TextField(max_length=1000, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
